Validator integration
airswap/airswap-web pull request #258
Opened 2021-10-27 23:50 UTC by hmalik88

Closes #210 

Integration of the `Validator` contract into the web app. The `ErrorList` component was created to display the errors returned from our `Validator` contract and is rendered into the `SwapWidget` through the `Overlay` component.

Would appreciate some guidance with the styling as you can see it's not that great ATM, I tried my best to replicate the Figma design.

NOTE: This integration is pre-launch and will be updated with `checkSwap` calls to the `Light` contract, the `Validator` repo is currently deprecated.

2021-10-30 02:37 UTC, piersss reviewed
I think I need to refactor the Overlay component to include scrolling for better reusability. I can make a branch based on your branch, ok?

2021-10-30 02:37 UTC, piersss commented on src/components/Overlay/Overlay.tsx
> +          {!!subTitle && !isHidden && (
Removing it when `isHidden` will warp the close animation. This should be animated with css, just like the title.

2021-10-30 02:37 UTC, piersss commented on src/components/ErrorList/ErrorList.tsx
> +import { ScrollContainer, Container } from "../TokenList/TokenList.styles";
You're using styled components from TokenList. We should refactor this and move ScrollContainer and Container to Overlay/Overlay.styles.

2021-10-30 06:06 UTC, hmalik88 commented
> I think I need to refactor the Overlay component to include scrolling for better reusability. I can make a branch based on your branch, ok?

Yeah, that's fine by me.

2021-11-01 23:25 UTC, gpxl-dev requested changes
Looks mostly good, a couple of changes I'd suggest:

1. Would prefer less duplication in `LastLook.tsx` - suggest renaming `getCurrentOrder` to `getSignedOrder`, and then changing the arguments for `sendOrderForConsideration` to just a `locator` (`string`) and an `order` (`LightOrder`)
2. The `errors` state variable should probably be explicitly `validatorErrors` or `validationErrors` for clarity. 
3. Is `Validator.ts` going to be in `@airswap/libraries` at some stage? 

I haven't checked through the styling / jsx as I assume piers has covered this already!

2021-11-01 23:52 UTC, hmalik88 commented
> Looks mostly good, a couple of changes I'd suggest:
> 
> 1. Would prefer less duplication in `LastLook.tsx` - suggest renaming `getCurrentOrder` to `getSignedOrder`, and then changing the arguments for `sendOrderForConsideration` to just a `locator` (`string`) and an `order` (`LightOrder`)
> 2. The `errors` state variable should probably be explicitly `validatorErrors` or `validationErrors` for clarity.
> 3. Is `Validator.ts` going to be in `@airswap/libraries` at some stage?
> 
> I haven't checked through the styling / jsx as I assume piers has covered this already!

Will do to the suggested changes and `Validator.ts` will not be in libraries, next iteration of `Light` will house the `checkSwap` function.

2021-11-01 23:54 UTC, gpxl-dev commented
Gotcha thanks!

2021-11-02 11:53 UTC, gpxl-dev approved these changes
Looks good - not sure about merging while Validator still shows swaps as unauthorized.

2021-11-02 15:13 UTC, gpxl-dev commented
Updated to fix last look swaps, and to skip the validator for wrapper swaps (because of the `senderWallet` balance check - since removed in the version within the new swap contract).

Now works with all 3 types.

2021-11-02 16:53 UTC, codyenokida approved these changes

2021-11-02 16:57 UTC, merged