Remove bookmark warning
airswap/airswap-web pull request #328
Opened 2021-11-05 17:26 UTC by gpxl-dev

Closes #327

2021-11-06 04:40 UTC, piersss requested changes
Also remove from userSettingsSlice.ts

2021-11-08 07:54 UTC, robbestad commented
Why not just redesign the component so that it fits in with the new design instead of removing all handling?

2021-11-08 13:57 UTC, gpxl-dev commented
@robbestad - think it's just because of availability of design resources, plus based on discord chat we're not actually sure if it's required.

Because of the nature of git, this stuff isn't lost, we can just revert the commit if/when we're ready to re-implement?

My original approach was to temporarily remove it but keep logic, but I guess that's a good way to collect legacy code that is no longer used!

2021-11-09 16:33 UTC, robbestad approved these changes

2021-11-09 23:13 UTC, merged