[Fix] Transactions tab slide in
airswap/airswap-web pull request #339
Opened 2021-11-09 00:57 UTC by codyenokida

- changed transactions tab styling
- One bug: blur background is rerenders when swap widget moves position

https://user-images.githubusercontent.com/30182368/140841948-b14ec274-6e6b-46f7-bcb5-6de8e7291386.mov

Are there any recommendations to fix this?

2021-11-09 03:02 UTC, piersss requested changes
Hey cody. Transition looks great. Not sure how we can fix the glow, maybe we should use a png as background. It's barely noticeable on my screen though.

I checked half of the code since I ran out of time, will finish later.

2021-11-09 07:38 UTC, robbestad commented
On firefox the gear icon is partially hidden
![bilde](https://user-images.githubusercontent.com/1560743/140881916-feddff63-1da7-4c21-8443-36c052c84ade.png)

2021-11-09 07:41 UTC, robbestad commented
I think you can remove the event listeners at https://github.com/airswap/airswap-web/blob/3166085a598d0c0b0876b6ebe7c3ae3aae815caa/src/components/TransactionsTab/TransactionsTab.tsx#L101 if it's supposed to be kept open

2021-11-09 12:57 UTC, piersss commented on src/components/TransactionsTab/TransactionsTab.tsx
> +              <LegendLine>{t("wallet:activeTransactions")}</LegendLine>
Fix the translation for activeTransactions and completedTransactions to "Active" and "Completed", and use style `text-transform: uppercase` in css.

2021-11-09 21:57 UTC, codyenokida commented
closes #287

2021-11-09 22:48 UTC, gpxl-dev requested changes
Looks great - three minor comments plus a change needed for short ENS names manifesting in the issue reported by Sven on discord.

2021-11-09 22:48 UTC, gpxl-dev commented on src/components/Icon/icons/IconChevronRight.tsx
> +      fill="white"
I think this should be `currentcolor` which means that the fill is the same as the CSS text colour. This makes it easier to change the colour of the icons (e.g. in light mode). P.S. I learned this from @piersss' code, thanks!

2021-11-09 22:48 UTC, gpxl-dev commented on src/components/Icon/icons/IconChevronRight.tsx
> +  className = "",
`className` isn't used - for other icons, `className={className}` is added to the `svg` elements, so I did this to mine for consistency!

2021-11-09 22:48 UTC, gpxl-dev commented on src/components/TransactionsTab/TransactionsTab.tsx
>                      key={transaction.hash}
not all transacitons in this list will have a hash. Suggest:

```
{`${transaction.hash}-${transaction.nonce}-${transaction.expiry}`}
```

Same for below.

2021-11-10 00:09 UTC, gpxl-dev approved these changes
Looks awesome!

2021-11-10 00:16 UTC, merged