Fix/343 light theme update
airswap/airswap-web pull request #397
Opened 2021-11-12 09:48 UTC by piersss

Closes #343 

- Updated light theme to new design
- Restored settings menu

2021-11-12 10:04 UTC, robbestad commented
Looking real good!
It needs an alternate image for light mode in mobile view:
![bilde](https://user-images.githubusercontent.com/1560743/141449040-8290e157-79f1-4698-9a61-c62a8ab27e93.png) (and white text on the text between the logo and "select destination")

2021-11-12 10:39 UTC, robbestad requested changes
Looking very good. Have a comment on light mode in mobile view here https://github.com/airswap/airswap-web/pull/397#issuecomment-966976430

2021-11-12 13:49 UTC, piersss commented
> Looking very good. Have a comment on light mode in mobile view here [#397 (comment)](https://github.com/airswap/airswap-web/pull/397#issuecomment-966976430)

Thanks! Jop will give me new image for light mode later today.

2021-11-14 11:40 UTC, robbestad approved these changes

2021-11-15 02:43 UTC, merged