405: lighthouse score improvements
airswap/airswap-web pull request #407
Opened 2021-11-18 02:09 UTC by piersss

Closes #405 

Just some low hanging fruit here.

- Accessibility and Best Practices are in the green now
- Not able to fix the main Performance issues, one is caused by typekit and the other is something about React.lazy(). Oh well.
- Removed unused DarkModeSwitch component

2021-11-18 08:06 UTC, robbestad requested changes
I commented only one place, but use translations for all ariaLabels.

2021-11-18 08:06 UTC, robbestad commented on src/components/SwapWidget/InfoSection.tsx
> +              ariaLabel="More information"
use translations for these

2021-11-18 09:37 UTC, piersss commented on src/components/SwapWidget/InfoSection.tsx
> +              ariaLabel="More information"
Whoopsy!

2021-11-19 08:14 UTC, robbestad commented
Very nice that you added keys for nb locale! Do you mind if I just change the wording for a couple of them by pushing onto this branch?

2021-11-20 02:26 UTC, piersss commented
> Very nice that you added keys for nb locale! Do you mind if I just change the wording for a couple of them by pushing onto this branch?

Yeah sure!

2021-11-20 09:07 UTC, robbestad approved these changes

2021-11-20 14:05 UTC, merged