Added a new route /whitepaper and refactored the Page component - Issue 380
airswap/airswap-web pull request #460
Opened 2022-01-26 05:13 UTC by Phasor

Changes made in relation to Github airswap-web issue 380:

1. Refactored the Page Component
- not tightly coupled with the SwapWidget component anymore
- Page component is now a generic page template, that we can inject child components into (like Whitepaper)

2. Added /whitepaper route
- added Whitepaper component and added route to App.tsx

2022-01-26 09:52 UTC, dmosites commented
Thanks @Phasor! The whitepaper is currently just HTML / CSS with some images as attached. Also fine if the URL ends up being `airswap.io/whitepaper.htm` if it doesn't fit into the current structure.
[whitepaper.zip](https://github.com/airswap/airswap-web/files/7940624/whitepaper.zip)

2022-01-26 12:22 UTC, robbestad requested changes

2022-01-27 12:31 UTC, piersss requested changes
Hello Phasor, welcome to the team!

I think the HomePage and Whitepaper should go in their own src/pages folder. Also try to use styled components and not place div's and a's in your components.

2022-01-27 12:31 UTC, piersss commented on src/components/Whitepaper/Whitepaper.tsx
> +            Download Airswap Whitepaper.
A translation should be added for this.

2022-01-28 00:46 UTC, closed without merging

2022-01-28 00:47 UTC, Phasor commented
Having issues with this branch. Closing and will open a new Issue 380 PR from a new branch.