Issue 380 - /whitepaper route added as static HTML
airswap/airswap-web pull request #462
Opened 2022-01-28 21:19 UTC by Phasor

Had a few CSS conflict issues with the previous PR for this issue. Fixed on this branch.

2022-01-31 16:30 UTC, piersss requested changes
Hey again phasor!

I guess we could use pure css instead of styled components for this if the other developers are ok with it.

One nitpicky thing: could you use camelCase for the files in /public?

Also the toolbar was not designed for 7 buttons, so it doesn't fit anymore. But that is something beyond the scope of this ticket so I could fix that later.

2022-01-31 16:30 UTC, piersss commented on src/components/Toolbar/Toolbar.tsx
> +        <ToolbarButton
Use react-router for internal links in the app. So modify ToolbarButton so it accepts link as property and use react-router accordingly.

2022-01-31 16:30 UTC, piersss commented on src/components/Whitepaper/Whitepaper.tsx
> +    </>
```
return (
  <div dangerouslySetInnerHTML={{ __html: htmlContent }} />
);
```

2022-01-31 16:30 UTC, piersss commented on src/components/Toolbar/Toolbar.tsx
> +          text="Whitepaper"
Add a translation for whitepaper with `useTranslation`. Ask Don or Brigand to help you add it to poeditor.

Also the word whitepaper doesn't fit. Please contact design how to solve this.
![Screenshot 2022-01-31 at 16 53 54](https://user-images.githubusercontent.com/86911296/151829233-73a016a8-8d6b-47d2-942b-c6962680e1d5.png)

2022-02-02 04:55 UTC, piersss commented on src/components/Toolbar/Toolbar.tsx
> +        <ToolbarButton
No need for toolbar button anymore. So this is resolved.

2022-02-02 04:56 UTC, piersss commented on src/components/Toolbar/Toolbar.tsx
> +          text="Whitepaper"
No need for toolbar button anymore. So this is resolved.

2022-02-02 22:50 UTC, Phasor commented on src/components/Whitepaper/Whitepaper.tsx
> +    </>
Updated thanks

2022-02-04 09:50 UTC, piersss approved these changes
All good!

2022-02-05 04:41 UTC, merged