Feature/605 maker error handling
airswap/airswap-web pull request #607
Opened 2022-09-08 15:41 UTC by piersss

While working on the `createOtcOrder` the error handling was really bugging me because we get different formats of errors from airswap-protocols.

So I decided to add some new error handling and a new `isAppError` guard which we will first try out in the new otc feature.

I also added a new ErrorList component, the legacy one I moved to the SwapWidget subcomponents.

2022-09-16 15:53 UTC, coltraneyan requested changes
works well for me. added a few styling fixes

2022-09-16 15:53 UTC, coltraneyan commented on src/components/SwapWidget/subcomponents/ErrorList/subcomponents/ErrorListItem/ErrorListItem.styles.tsx
> +  margin-right: 1.125rem;
```suggestion
  margin-right: 1.125rem;
  color: ${({ theme }) =>
    theme.name === "dark" ? theme.colors.white : theme.colors.primary};
```

for Maker errors as well

2022-09-16 15:53 UTC, coltraneyan commented on public/locales/en/translation.json
> +    "swapFail": "The swap would fail for the following reasons.",
```suggestion
    "swapFail": "The swap would fail for the following reasons:",
```

2022-09-18 11:31 UTC, piersss commented on src/components/SwapWidget/subcomponents/ErrorList/subcomponents/ErrorListItem/ErrorListItem.styles.tsx
> +  margin-right: 1.125rem;
Fixed for both. 👍

2022-09-18 11:32 UTC, piersss commented on public/locales/en/translation.json
> +    "swapFail": "The swap would fail for the following reasons.",
Done.

2022-09-18 18:33 UTC, coltraneyan approved these changes

2022-09-18 18:34 UTC, merged