Fixed design issue
airswap/airswap-web pull request #680
Opened 2022-11-26 04:08 UTC by helloitsm3

Made changes to issues listed in PR #667

2022-11-28 11:01 UTC, piersss requested changes
Welcome CodePerfect. Got some feedback for ya!

2022-11-28 11:01 UTC, piersss commented on public/locales/en/translation.json
> +    "enterTokenAmount": "Enter amount",
And then also fix `getActionButtonTranslation` helper line 37 & 41.

2022-11-30 07:49 UTC, piersss commented on src/components/MakeWidget/MakeWidget.tsx
> +            takerAddressIsValid={takerAddressIsValid}
You have not added this yet. It still goes into error immediately.

2022-11-30 07:53 UTC, piersss requested changes
Hey Sean, please don't resolve other people's feedback next time. Thanks!

2022-11-30 07:53 UTC, piersss commented on src/components/MakeWidget/MakeWidget.styles.tsx
> +  border: ${(props) => !props?.hasError && "1px solid red"};
Move this styling inside the AddressInput component

2022-11-30 07:54 UTC, piersss commented on src/components/MakeWidget/MakeWidget.tsx
> +            </StyledTooltip>
This is not fixed yet.

2022-12-03 11:25 UTC, helloitsm3 commented
Closing this PR as it's getting really messy. Will make a new PR

2022-12-03 11:25 UTC, closed without merging