Fix/751 OTC back to ViewAllQuotes
airswap/airswap-web pull request #755
Opened 2023-04-25 16:51 UTC by coltraneyan

2023-05-02 19:54 UTC, piersss requested changes
Tested and got some feedback.

2023-05-02 19:54 UTC, piersss commented on src/components/OrderDetailWidget/OrderDetailWidget.tsx
> +    history.goBack();
```suggestion
    if (userIsFromSwapFlow) {
      history.goBack();

      return;
    }

    history.push({
      pathname: `/${userOrders.length ? AppRoutes.myOrders : AppRoutes.make}`,
    });
```

2023-05-02 19:54 UTC, piersss commented on src/components/OrderDetailWidget/OrderDetailWidget.tsx
> +    history.goBack();
I did this because else you will route away from the website when you land via a direct link.

2023-05-03 03:29 UTC, coltraneyan commented on src/hooks/useAppRouteParams.ts
> +    `/:route/:${SwapRoutes.tokenFrom}/:${SwapRoutes.tokenTo}/:${SwapRoutes.viewAllQuotesAmount}`
went with another instance of router state to avoid more state cleanup

2023-05-05 20:13 UTC, piersss commented on src/hooks/useAppRouteParams.ts
> +    `/:route/:${SwapRoutes.tokenFrom}/:${SwapRoutes.tokenTo}/:${SwapRoutes.viewAllQuotesAmount}`
I think using `fromSwapFlow` in location state is ok. But `searchAmount` should not be in location, that should be saved in the store. Also it doesn't get cleared after you change the amount in the SwapWidget again.

2023-05-05 20:15 UTC, piersss requested changes
Avoid glitchy behaviour when going back.

https://user-images.githubusercontent.com/86911296/236560137-b097317b-4027-481e-b11e-0540184f7974.mov

Where's this error coming from?

![Screenshot 2023-05-05 at 21 51 35](https://user-images.githubusercontent.com/86911296/236560308-d4285d5d-e5ca-4ad8-8408-79f17a6d81d9.png)

2023-05-24 15:06 UTC, closed without merging