Fixes732
airswap/airswap-web pull request #788
Opened 2023-06-19 21:04 UTC by personnamedmike

https://github.com/airswap/airswap-web/assets/90465420/74817c79-48ae-4dd6-80bd-f8211619ec44

2023-06-19 21:04 UTC, personnamedmike commented
Waiting on confirmation from design team that we're going with this design

2023-06-21 22:00 UTC, personnamedmike commented
Fixed up styling and added tooltip

https://github.com/airswap/airswap-web/assets/90465420/ad51c71e-c8af-4652-a531-15bd39f350c2

2023-07-05 17:56 UTC, dmosites requested changes

2023-07-05 17:56 UTC, dmosites commented on public/locales/en/translation.json
> +    "verifyEtherscan": "Verify on Etherscan",
Each chain has a different block explorer, so how about just "Verify token"?

2023-07-05 19:09 UTC, personnamedmike commented on public/locales/en/translation.json
> +    "verifyEtherscan": "Verify on Etherscan",
fixed

2023-07-12 14:25 UTC, dmosites approved these changes

2023-07-12 14:25 UTC, merged