Feature/toast notification
airswap/airswap-web pull request #87
Opened 2021-07-25 05:32 UTC by codyenokida

Toast notifications for transactions and approvals!

Notable changes:
1. installed react-hot-toast dependency
2. Two types of different toasts: TransactionToasts and Generic Toast
3. TransactionToast for all transactions and approval requests
4. Generic Toast for more generic error or warning messages.
2. Created a ToastController that exports functions to render Toasts
3. Created storybooks

Feedback appreciated!

2021-07-26 11:12 UTC, gpxl-dev commented
I haven't looked in huge detail at implementation yet, but I think this mostly needs to be discussed with the designers / someone with design authority, but there are a few things that differ a bit from designs (as well as general approach to toasts as per my thoughts on [discord](https://discord.com/channels/590643190281928738/832210263284383764/869163459361779782) :

1. Generic toast is much bigger than error message popup in design (font size, wise).
2. Close icon vertical centering on generic toast
3. Generic toast appears to be able to take some supplementary information (e.g. an error code), which isn't accounted for in its props currently.
4. Transaction toasts are fixed width in the designs

One implementation point I'm not sure about is that the start time is passed formatted to the toasts. I think this is a slightly jarring developer experience as, when I implement a toast, I need to reference the formatting on all other toasts, and similarly if I want to change the way the start time is displayed on a toast, I need to do it in many places. I would pass a javascript millisecond timestamp (i.e. `Date.now()`) and do the formatting in the toast itself.

Reference images:

Storybook tx toast:
![image](https://user-images.githubusercontent.com/82473383/126979635-f52a6013-394e-4892-ac5d-5551c432e163.png)

Design tx toast:
![image](https://user-images.githubusercontent.com/82473383/126979684-914263df-e7a5-43ad-83ef-4bb9acaacc45.png)

Storybook generic toast: 
![image](https://user-images.githubusercontent.com/82473383/126979755-5d82e4dd-fc05-401d-8217-4e1edd2dd551.png)

Design generic toast (not to scale, sorry):
![image](https://user-images.githubusercontent.com/82473383/126979819-f73ed775-7a85-4ec4-907e-efe184d98ef4.png)

Relative sizing of toasts on design:

![image](https://user-images.githubusercontent.com/82473383/126979959-6dbf6f9b-d6be-4591-b0d3-01848c3403c1.png)

2021-07-30 09:28 UTC, piersss requested changes

2021-07-30 09:28 UTC, piersss commented on src/components/Toasts/GenericToast.tsx
> +      <BiInfoCircle style={{ width: "1.5rem", height: "1.5rem" }} />
Move styling to GenericToast.styles.tsx

2021-07-30 09:28 UTC, piersss commented on src/components/Toasts/GenericToast.tsx
> +          style={{
This should be a button, not a div, and move styling to GenericToast.styles.tsx

2021-07-30 09:28 UTC, piersss commented on src/components/Toasts/GenericToast.styles.tsx
> +export const HiXContainer = styled.div<{ theme: ThemeProps }>``;
Vertically center the close button like so:

```
display: flex;
align-items: center;
```

2021-07-30 09:28 UTC, piersss commented on src/components/Toasts/ToastController.tsx
> +const formatDate = (date: Date) => {
`const formatDate = (date: Date): string => {`

Move this function to Toasts/helpers/formatDate.ts and write some tests in Toasts/helpers/formatDate.test.ts

2021-07-30 09:28 UTC, piersss commented on src/components/Toasts/Toaster.tsx
> +const ToasterWrapper = styled.div`
Move styles to Toaster.styles.tsx

2021-07-30 09:28 UTC, piersss commented on src/components/Toasts/TransactionToast.styles.tsx
> +  color: ${(props) => props.theme.colors.white};
Try to order your styling according to the box model. For instance `color` and `background` don't have any effect on the size / position of your, but `display` and `grid-template-columns` do.

```
  display: grid;
  grid-template-columns: auto auto auto;
  grid-gap: 1rem;
  justify-items: center;
  align-items: center;
  padding: 1rem;
  color: ${(props) => props.theme.colors.white};
  background: ${(props) => props.theme.colors.black};
```

2021-07-30 09:28 UTC, piersss commented on src/components/Toasts/TransactionToast.styles.tsx
> +  background: ${(props) =>
```
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 50%;
  width: 2rem;
  height: 2rem;
  color: white;
  background: ${(props) =>
    props.error ? props.theme.colors.red : props.theme.colors.primary};

```

2021-08-20 00:15 UTC, closed without merging